version: "3"
services: 
  backend-central:
    image: backend-central
    ports:
      - "5000:5000"
    depends_on: 
      - mongo
    networks: 
      - mern-central
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks: 
      - mern-central
    volumes:
      - mongo-data:/data/db
networks: 
  mern-central:
    driver: bridge
volumes: 
  mongo-data:
    driver: local